### ISSUE TITLE
Allow group reuse

### ISSUE THREAD

**Issue by mark-au** [oracle-terraform-modules/terraform-oci-ocne#10]
An OCI user may not have permissions to create/delete a dynamic group and only permissions to update an existing dynamic group. 

This RFE is to allow an existing dynamicgroup (declared in terraform.tfvars) to be re-used instead of creating and deleting a new dynamic group each time.

**Comment by mark-au** [comment]
AFAIK the dynamic group is only used to limit access to a secret. It may be better to instead avoid the use of secrets as it's only to allow ssh between operator and master/worker nodes in x.509 cert deployment. Distributing certs in another way would remove the need for this privilege, good for pipelines running this code.

**Comment by scoter-oracle** [comment]
Please, check if this issue can be reproduced with latest code release.
