### ISSUE TITLE
Deployment nginx-nginx-ingress-nginxdefaultbackend does not become ready

### ISSUE THREAD

**Issue by mark-au** [oracle-terraform-modules/terraform-oci-ocne#5]
Deployment nginx-nginx-ingress-nginxdefaultbackend fails health checks and never comes online

`Warning  Unhealthy  96s (x14 over 2m41s)  kubelet, dev-worker-453184  Readiness probe failed: Get http://10.244.2.2:31080/healthz: dial tcp 10.244.2.2:31080: connect: connection refused`

**Comment by scoter-oracle** [comment]
Please, check if this issue can be reproduced with latest code release.
